import { motion } from 'framer-motion';
import { BarChart3, BrainCircuit, GitBranch, Radar, Route, ShieldCheck } from 'lucide-react';
import Hero from '@/components/Hero';

const FEATURES = [
  {
    icon: BarChart3,
    title: 'Repository Analytics',
    description: 'Stars, forks, language distribution, and activity patterns pulled straight from the GitHub REST API.',
  },
  {
    icon: Radar,
    title: 'Developer Score',
    description: 'A 0–100 composite score weighing repositories, community traction, modern-stack usage, and consistency.',
  },
  {
    icon: BrainCircuit,
    title: 'AI Career Insights',
    description: 'Strengths, gaps, engineering level, and a suggested role — generated by a pluggable AI service layer.',
  },
  {
    icon: Route,
    title: 'Learning Roadmap',
    description: 'A staged roadmap with technologies, project ideas, certifications, and estimated score improvement.',
  },
  {
    icon: GitBranch,
    title: 'Rule-Based Skill Detection',
    description: 'Detects React, Node, Docker, testing, CI/CD and more directly from repo names, topics, and descriptions.',
  },
  {
    icon: ShieldCheck,
    title: 'Interview Readiness',
    description: 'A readiness score plus targeted notes on what to brush up on before your next technical interview.',
  },
];

const STEPS = [
  { title: 'Enter a username', description: 'Paste any public GitHub handle — yours, a teammate\u2019s, or a candidate\u2019s.' },
  { title: 'We analyze the profile', description: 'CodeDNA pulls repos, computes the Developer Score, and detects your stack.' },
  { title: 'Get AI-generated insights', description: 'Review strengths, gaps, a suggested role, and a personalized roadmap.' },
];

export default function LandingPage() {
  return (
    <>
      <Hero />

      <section id="features" className="mx-auto max-w-6xl px-6 py-20">
        <div className="mb-12 text-center">
          <h2 className="text-3xl font-semibold text-white sm:text-4xl">
            Everything you need to <span className="gradient-text">read the signal</span>
          </h2>
          <p className="mx-auto mt-3 max-w-xl text-slate-400">
            One profile in, a full engineering growth report out.
          </p>
        </div>

        <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
          {FEATURES.map((f, i) => (
            <motion.div
              key={f.title}
              initial={{ opacity: 0, y: 16 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: '-60px' }}
              transition={{ duration: 0.45, delay: i * 0.05 }}
              className="glass-card group p-6 transition-colors hover:border-white/[0.14]"
            >
              <div className="mb-4 flex h-10 w-10 items-center justify-center rounded-lg bg-gradient-to-br from-accent-violet/25 to-accent-magenta/25 text-accent-violet transition-transform group-hover:scale-105">
                <f.icon size={20} />
              </div>
              <h3 className="mb-1.5 text-base font-semibold text-white">{f.title}</h3>
              <p className="text-sm leading-relaxed text-slate-400">{f.description}</p>
            </motion.div>
          ))}
        </div>
      </section>

      <section id="how-it-works" className="mx-auto max-w-4xl px-6 pb-24">
        <div className="mb-12 text-center">
          <h2 className="text-3xl font-semibold text-white sm:text-4xl">How it works</h2>
        </div>
        <div className="space-y-6">
          {STEPS.map((step, i) => (
            <motion.div
              key={step.title}
              initial={{ opacity: 0, x: -12 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true, margin: '-60px' }}
              transition={{ duration: 0.4, delay: i * 0.08 }}
              className="glass-card flex items-start gap-5 p-6"
            >
              <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full border border-accent-violet/30 bg-accent-violet/10 font-mono text-sm text-accent-violet">
                {i + 1}
              </span>
              <div>
                <h3 className="mb-1 text-base font-semibold text-white">{step.title}</h3>
                <p className="text-sm text-slate-400">{step.description}</p>
              </div>
            </motion.div>
          ))}
        </div>
      </section>
    </>
  );
}
